-- 0201_storage_policies.sql
-- Farm-scoped RLS on storage.objects for the private app buckets. Object paths are
-- `{farm_id}/{machine_id}/{file}`, so access is gated by the first path segment
-- (the farm id) via app.has_farm_access(). Signed URLs generated by an authenticated
-- user therefore work only for that user's farms. Guarded so it's a no-op on a local
-- Postgres that has no `storage` schema.

do $do$
begin
  if not exists (select 1 from information_schema.schemata where schema_name = 'storage') then
    return;
  end if;

  execute 'drop policy if exists "farmgear objects read"   on storage.objects';
  execute 'drop policy if exists "farmgear objects insert" on storage.objects';
  execute 'drop policy if exists "farmgear objects update" on storage.objects';
  execute 'drop policy if exists "farmgear objects delete" on storage.objects';

  execute $p$
    create policy "farmgear objects read" on storage.objects for select to authenticated
    using (bucket_id in ('machine-photos','machine-docs','fault-photos','jobcard-photos')
           and app.has_farm_access(nullif((storage.foldername(name))[1], '')::uuid))
  $p$;
  execute $p$
    create policy "farmgear objects insert" on storage.objects for insert to authenticated
    with check (bucket_id in ('machine-photos','machine-docs','fault-photos','jobcard-photos')
           and app.has_farm_access(nullif((storage.foldername(name))[1], '')::uuid))
  $p$;
  execute $p$
    create policy "farmgear objects update" on storage.objects for update to authenticated
    using (bucket_id in ('machine-photos','machine-docs','fault-photos','jobcard-photos')
           and app.has_farm_access(nullif((storage.foldername(name))[1], '')::uuid))
  $p$;
  execute $p$
    create policy "farmgear objects delete" on storage.objects for delete to authenticated
    using (bucket_id in ('machine-photos','machine-docs','fault-photos','jobcard-photos')
           and app.has_farm_access(nullif((storage.foldername(name))[1], '')::uuid))
  $p$;
end $do$;
