-- 20260911190000_email_verification.sql
-- The email address was never checked, and everything depends on it.
--
-- WHAT DEPENDS ON IT
-- ─────────────────────────────────────────────────────────────────────────────
-- `/signup` creates the auth user with `email_confirm: true`, so the address is trusted on
-- sight. That address is the only place the receipt goes, the only place a failed-payment
-- warning goes, and — because password recovery in this product IS the magic link ("use
-- the sign-in link instead — it works without one") — the only way back into the account.
--
-- One typo at sign-up therefore means: no receipts, no dunning warning, and a lockout that
-- only Rapid Rise can undo. For somebody paying every month, that is not a small thing.
--
-- WHY NOT JUST SET email_confirm TO FALSE
-- ─────────────────────────────────────────────────────────────────────────────
-- Because `signUp` signs them in immediately and sends them to `/activate` to pay, and an
-- unconfirmed Supabase user cannot sign in. Making the address block the sign-in would put
-- an email round trip between "I want to buy this" and "here is my card", which is the
-- wrong place to add friction for a product bought by farmers on a phone in a shed.
--
-- So the auth user stays confirmed and the VERIFICATION IS OURS: a token we mint, email and
-- check. It gates nothing; it tells the truth about whether the address works, prompts
-- until it does, and makes a wrong one fixable.
--
-- WHY A HASH AND NOT THE TOKEN
-- ─────────────────────────────────────────────────────────────────────────────
-- `public.users` is readable by the rest of the farm — that is what the team screen is —
-- and RLS filters ROWS, not COLUMNS. This project has already been caught by exactly that
-- distinction once, when `ALTER DEFAULT PRIVILEGES` left `authenticated` able to read
-- `billing_payment_methods.authorization_code` (SECURITY.md §2b). A colleague reading a
-- verification token could confirm somebody else's address, so only its SHA-256 is stored
-- and the token itself exists in one email and nowhere else.
--
-- Single use is the hash being cleared on success. Expiry is `email_verify_sent_at` plus a
-- window the route applies, so a link forwarded or left in an old mailbox stops working.

begin;

alter table public.users
  add column if not exists email_verified_at    timestamptz,
  add column if not exists email_verify_hash    text,
  add column if not exists email_verify_sent_at timestamptz;

comment on column public.users.email_verified_at is
  'When this person proved they can receive mail at users.email. Null means unproven, not '
  'invalid — it gates nothing, it prompts.';
comment on column public.users.email_verify_hash is
  'SHA-256 (hex) of the outstanding verification token, never the token. Cleared on success, '
  'which is what makes the link single-use.';

-- Everyone who exists right now has been reachable by mail in practice — the demo accounts
-- were re-pointed at a real inbox and every one was verified by an actual sign-in — so they
-- start verified rather than being nagged for something already true. New sign-ups start
-- null and are asked.
update public.users
   set email_verified_at = coalesce(email_verified_at, created_at)
 where email is not null and email <> '' and deleted_at is null;

-- ── Minting ──────────────────────────────────────────────────────────────────
-- Service-role only, and it deliberately takes the HASH rather than the token: the token is
-- generated by the caller, goes straight into the email, and never touches the database. A
-- function that generated it would have to return it, which puts it in a query log.
create or replace function app.set_email_verification(p_user uuid, p_hash text)
returns void
language sql security definer set search_path = public, pg_temp as $$
  update public.users
     set email_verify_hash = p_hash,
         email_verify_sent_at = now()
   where id = p_user;
$$;

revoke execute on function app.set_email_verification(uuid, text) from public, anon, authenticated;
grant  execute on function app.set_email_verification(uuid, text) to service_role;

-- ── Redeeming ────────────────────────────────────────────────────────────────
-- Takes the hash and the window, matches at most one row, and reports what happened in
-- words rather than as a boolean: "already done" and "no such token" are different things
-- to tell somebody who has just clicked a link, and an expired link deserves its own
-- sentence with a way to get a new one.
create or replace function app.verify_email_token(p_hash text, p_max_age_hours integer default 72)
returns text
language plpgsql security definer set search_path = public, pg_temp as $fn$
declare u public.users%rowtype;
begin
  if p_hash is null or length(p_hash) <> 64 then return 'invalid'; end if;

  select * into u from public.users
   where email_verify_hash = p_hash and deleted_at is null
   for update;

  if not found then
    -- Either never issued, or already redeemed and cleared. Both are 'invalid' to the
    -- caller: distinguishing them would confirm that a token once existed.
    return 'invalid';
  end if;

  if u.email_verified_at is not null then
    update public.users set email_verify_hash = null where id = u.id;
    return 'already';
  end if;

  if u.email_verify_sent_at is null
     or u.email_verify_sent_at < now() - make_interval(hours => p_max_age_hours) then
    return 'expired';
  end if;

  update public.users
     set email_verified_at = now(),
         email_verify_hash = null
   where id = u.id;

  return 'verified';
end;
$fn$;

revoke execute on function app.verify_email_token(text, integer) from public, anon, authenticated;
grant  execute on function app.verify_email_token(text, integer) to service_role;

-- Both wrappers are service-role only. The verification route runs with the service client
-- because the person clicking the link is not necessarily signed in — that is the whole
-- point of a link in an email — so there is no session for RLS to scope by, and the token
-- IS the authorisation.
create or replace function public.set_email_verification(p_user uuid, p_hash text)
returns void
language sql security definer set search_path = public, pg_temp as $$
  select app.set_email_verification(p_user, p_hash);
$$;
revoke execute on function public.set_email_verification(uuid, text) from public, anon, authenticated;
grant  execute on function public.set_email_verification(uuid, text) to service_role;

create or replace function public.verify_email_token(p_hash text, p_max_age_hours integer default 72)
returns text
language sql security definer set search_path = public, pg_temp as $$
  select app.verify_email_token(p_hash, p_max_age_hours);
$$;
revoke execute on function public.verify_email_token(text, integer) from public, anon, authenticated;
grant  execute on function public.verify_email_token(text, integer) to service_role;

commit;
